### ISSUE TITLE
Can't maximise

### ISSUE THREAD

**Issue by eliocamp** [lainsce/quilter#13]
Clicking the maximise button, double clicking the header or pressing super + up doesn't do anything. Right cliclk -> maximise does, but it just removes the border.

PS: This is a great looking app and I hope it grows to be an excellent replacement for (the mostly defunct) Uberwritter. Thanks!

**Comment by lainsce** [comment]
Did you update to 1.0.4?
Most users with those problems with the maximize state, got resolved with that version.

**Comment by eliocamp** [comment]
Yep. I've got the AppStore version.

**Comment by lainsce** [comment]
Let's try something. :smile:
Uninstall and reinstall the app and check if those problems occur again.

**Comment by eliocamp** [comment]
Still not working :\ 

I get some warnings in the command line. Maybe it could help.
```
 com.github.lainsce.quilter
[INFO 19:27:07.239146] Application.vala:153: Quilter version: 1.0.4
[INFO 19:27:07.239213] Application.vala:155: Kernel version: 4.4.0-79-generic
[WARNING 19:27:07.288056] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 19:27:07.288123] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 19:27:07.288191] [Gtk] Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
```

**Comment by lainsce** [comment]
I've reinstalled and installed the app here, removing any traces of it when I uninstalled.
Maximize is working normally.
Maybe there's something happening on your pantheon session that's making maximize not work.

(Those warnings are of the elementary OS GTK style, they're not related to my app.)

**Comment by lainsce** [comment]
I'm going to close this issue as I believe it's not under my app the problem.
Try filing a bug at elementary/gala about maximize not working in certain apps.

**Comment by Djaler** [comment]
I can confirm it too

**Comment by lainsce** [comment]
I can't fix this issue, as it isn't the problem on Quilter, but the window manager in your specific hardware.

**Comment by Djaler** [comment]
But why it occurs only with your app?

**Comment by lainsce** [comment]
That's a good question, I really don't know. I use the same maximization/fullscreen code as all the other apps in GTK3 Vala.
