### ISSUE TITLE
Contents not saved?

### ISSUE THREAD

**Issue by peteruithoven** [lainsce/quilter#220]
The contents of notes does not seem to be saved. 

1. Open Quilter
2. Write some text.
3. Close Quilter
4. Reopen Quilter, no text is shown.

When I explicitly use save as the file is saved, but I need to manually reopen that file. 

Where should the data be stored? I'd love to check if anything is saved.

I'd also be happy to manually compile a new version and test things. 

I'm using Quilter 1.7.0.

**Comment by lainsce** [comment]
Can you check if Quilter 1.7.2 has the same issue?

**Comment by peteruithoven** [comment]
Compiled from master, I'm seeing mostly the same issue.
It did now automatically a manually (saved as) file. 

I did see these errors when running it from the terminal:
```
** (com.github.lainsce.quilter:6608): WARNING **: 22:40:20.453: SideBar.vala:66: Error: Error reading file “/home/peteruithoven/Projects/elementary/com.github.lainsce.quilter/build”: Is a directory

Error writing file: Failed to rename file “.L6MVXZ” to “”: g_rename() failed: No such file or directory% 
```

**Comment by cassidyjames** [comment]
@lainsce reproducible here for me in 1.7.2.

**Comment by lainsce** [comment]
I see. I'll investigate and fix this soon and also do a new release before next friday.

**Comment by peteruithoven** [comment]
Not sure what happened, but no longer seeing that error. 

I have enabled debug logging and seeing these a lot of these:
```
** (com.github.lainsce.quilter:7752): DEBUG: 22:48:54.248: FileManager.vala:116: Saving file...
** (com.github.lainsce.quilter:7752): DEBUG: 22:48:54.248: FileManager.vala:118: User cancelled operation. Aborting.
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:04.252: FileManager.vala:111: Save button pressed.
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:04.252: FileManager.vala:116: Saving file...
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:04.252: FileManager.vala:118: User cancelled operation. Aborting.
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:14.256: FileManager.vala:111: Save button pressed.
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:14.256: FileManager.vala:116: Saving file...
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:14.256: FileManager.vala:118: User cancelled operation. Aborting.
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:24.265: FileManager.vala:111: Save button pressed.
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:24.265: FileManager.vala:116: Saving file...
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:24.265: FileManager.vala:118: User cancelled operation. Aborting.
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:34.266: FileManager.vala:111: Save button pressed.
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:34.266: FileManager.vala:116: Saving file...
** (com.github.lainsce.quilter:7752): DEBUG: 22:49:34.266: FileManager.vala:118: User cancelled operation. Aborting.
```

**Comment by peteruithoven** [comment]
Looks like the error I mentioned earlier happens when starting a new file. When I start a new file and say not to store the currently open file, I see these logs:
```
Gtk-Message: 22:56:40.885: GtkDialog mapped without a transient parent. This is discouraged.

(com.github.lainsce.quilter:8312): Gtk-WARNING **: 22:56:40.886: gtk_window_set_titlebar() called on a realized window
Gtk-Message: 22:56:40.889: GtkDialog mapped without a transient parent. This is discouraged.
** (com.github.lainsce.quilter:8312): DEBUG: 22:56:42.557: HeaderBar.vala:77: User doesn't care about the file, shoot it to space.

** (com.github.lainsce.quilter:8312): WARNING **: 22:56:42.935: SideBar.vala:66: Error: Error reading file “/home/peteruithoven/Projects/elementary/com.github.lainsce.quilter/build”: Is a directory

** (com.github.lainsce.quilter:8312): DEBUG: 22:56:46.222: FileManager.vala:111: Save button pressed.
** (com.github.lainsce.quilter:8312): DEBUG: 22:56:46.222: FileManager.vala:116: Saving file...
Error writing file: Failed to rename file “.OTKQXZ” to “”: g_rename() failed: No such file or directory** (com.github.lainsce.quilter:8312): DEBUG: 22:56:56.225: FileManager.vala:111: Save button pressed.
** (com.github.lainsce.quilter:8312): DEBUG: 22:56:56.225: FileManager.vala:116: Saving file...
** (com.github.lainsce.quilter:8312): DEBUG: 22:56:56.225: FileManager.vala:118: User cancelled operation. Aborting.
```

**Comment by peteruithoven** [comment]
I think the issue is that `/home/peteruithoven/.local/share/com.github.lainsce.quilter/` doesn't exist.

**Comment by lainsce** [comment]
Oh, so it is way easier than I thought
I just need to force the directory to exist always.

**Comment by lainsce** [comment]
There are some Sidebar bugs related to this.

**Comment by lainsce** [comment]
Fixed.

**Comment by peteruithoven** [comment]
I'm afraid it's not. 
When booting I'm seeing:
```
** (com.github.lainsce.quilter:9210): WARNING **: 09:46:46.062: SourceView.vala:99: Error: Failed to open file “/home/peteruithoven/.local/share/com.github.lainsce.quilter/temp.md”: No such file or directory
```
When I press the new file button
```
Gtk-Message: 09:47:08.105: GtkDialog mapped without a transient parent. This is discouraged.

(com.github.lainsce.quilter:9210): Gtk-WARNING **: 09:47:08.106: gtk_window_set_titlebar() called on a realized window
Gtk-Message: 09:47:08.110: GtkDialog mapped without a transient parent. This is discouraged.
** (com.github.lainsce.quilter:9210): DEBUG: 09:47:10.367: HeaderBar.vala:86: User doesn't care about the file, shoot it to space.

** (com.github.lainsce.quilter:9210): WARNING **: 09:47:10.369: SideBar.vala:74: Error: Failed to open file “/home/peteruithoven/.local/share/com.github.lainsce.quilter/temp.md”: No such file or directory
```

**Comment by lainsce** [comment]
I made sure that file folder and the temp.md file is always being made on first app opening. Try building on a clean clone of the repo.

**Comment by cassidyjames** [comment]
@lainsce just cloned for the first time on this machine and compiled from source, and I'm still seeing issues where files aren't getting saved and switching between things in the sidebar is blowing away my changes.

**Comment by lainsce** [comment]
Bug squashed! :joy:

**Comment by imasaru** [comment]
@lainsce I was running Quilter v1.8.2 when I lost all of my work today... Before and after reinstalling, I receive the same error as @peteruithoven: 

> ```
> ** (com.github.lainsce.quilter:9210): WARNING **: 09:46:46.062: SourceView.vala:99: Error: Failed to open file “/home/peteruithoven/.local/share/com.github.lainsce.quilter/temp.md”: No such file or directory
> ```

I also performed @peteruithoven's  1–5 test multiple times on different sets of text and still got the same error.
