### ISSUE TITLE
CORE DUMP: Error removing file

### ISSUE THREAD

**Issue by mryodo** [lainsce/quilter#28]
Steps to reproduce:

1. Launch Qiulter
2. Add any text 
3. Wait till it crashes

Console:
```
[ERROR 04:29:32.735292] FileUtils.vala:110: Error removing file: Permission denied
[1]    16444 trace trap (core dumped)  com.github.lainsce.quilter
```

On superuser run with same steps, console errors are:
```
[ERROR 04:32:44.331353] FileUtils.vala:110: Error removing file: Directory not empty
[1]    16639 trace trap (core dumped)  sudo com.github.lainsce.quilter
```

System: Elementary OS 0.4.1, nearly clean install.
App installed via App Center

**Comment by lainsce** [comment]
Which version of Quilter are you running?
If it's version 1.1.6, then I fixed this bug.

**Comment by mryodo** [comment]
Actually, i'm sirt of confused about that.
I've upgraded (and then removed and re-installed) Quilter from AppCenter, which implies version 1.1.6.
But console says:
```
[INFO 05:33:52.572256] Application.vala:153: Quilter version: 1.1.4
[INFO 05:33:52.572319] Application.vala:155: Kernel version: 4.8.0-58-generic
```

**Comment by lainsce** [comment]
Yeah, then it's not version 1.1.6, wait for the AppCenter to catch the new version for you and see if your bug is fixed 😄

**Comment by mryodo** [comment]
thanx!

**Comment by mryodo** [comment]
Sorry, but still getting the same thing (even with built from source for v.1.1.7)
Maybe, sth is wrong with me, not app...
