### ISSUE TITLE
Spellchecking doesn't show in the Editor

### ISSUE THREAD

**Issue by jimbojim** [lainsce/quilter#337]
## The spellchecking extension is not working
I have enabled spellchecking  in the extensions section of preferences and I am unable to see incorrect spelling highlighted in edit or preview mode.

OS: Arch Linux
Quilter version: quilter 2.2.2-1 installed from the Arch User Repository (AUR)

![Screenshot from 2020-05-14 11-33-38](https://user-images.githubusercontent.com/49759175/81954514-f2f67700-95d6-11ea-84f5-1edd8eb9be19.png)

**Comment by jimbojim** [comment]
I also just removed quilter and installed quilter-git instead. The same behavior is present.

[xxxx@xxxx ~]$ pacman -Q quilter
quilter-git r586.c2ad09a-1

**Comment by lainsce** [comment]
What does right-clicking and selecting your language under the Languages option do? Try out en-us option; does it show the misspellings with red squiggly lines?

**Comment by jimbojim** [comment]
I installed quilter from source on my ubuntu laptop as well and seem to have the same problem. I've selected en_US. I see suggestions when I right click a misspelled word, but the red squiggly lines do not show.

**Comment by jimbojim** [comment]
Here is a screenshot of what I'm seeing.
![Screenshot from 2020-05-14 14-10-48](https://user-images.githubusercontent.com/49759175/81970320-54c1db80-95ed-11ea-9fef-178bfced7fd7.png)

**Comment by lainsce** [comment]
OK, I'll solve this soon :P

**Comment by lainsce** [comment]
Update: I have found out that this happens only on newly typed text, not loaded text from a previous state.

**Comment by Brin-o** [comment]
Hi, i'd like to add here that spellchecking extension is not "hotswappable". I'd also like to hijack this thread to ask how I could help providing more flanges. My language (SI-Slovenian) is not supported in the spellchecker and I'd love to have it be added in.

**Comment by lainsce** [comment]
Languages should appear in you install missing ones via the Switchboard plug.

**Comment by lainsce** [comment]
Fixed in #338

**Comment by janxkoci** [comment]
I have two laptops and for some reason, the spell-check only works on one of them. The Language selection in right click menu is also missing on the laptop without spell-check. I tried to install languages from switchboard but no luck, still doesn't work.

**Comment by lainsce** [comment]
No clue what happened there. Maybe there's still some missing spellchecker packages that weren't installed?

**Comment by janxkoci** [comment]
No clue either - both laptops show the same dependencies for Quilter as installed. The spell check should be done by `libgtkspell3-3-0` right?

**Comment by lainsce** [comment]
Yeah, that should be it. Perhaps there's some translatable text missing for your language, that needs to be translated for this to appear? I know PDF export stuff has this which is dumb.

**Comment by janxkoci** [comment]
So I tried installing Dconf editor to see if there is some messed up setting - and there was! The language set for Quilter spell check was set to `'All_Upper Case'` - changing it to `'en_GB'` fixed the issue and spell check now works on both laptops :smile:

**Comment by lainsce** [comment]
Aesop shouldn't mess with spellchecking :p

Glad you got it fixed :tada:

**Comment by janxkoci** [comment]
Yeah I realised later I don't even have it installed anymore :smile: 

And I'm happy I have the spell check finally fixed - no idea how it got that value there :sweat_smile:

**Comment by lainsce** [comment]
Maybe some other app messed it up.

Anyhow, locking this issue since the issue got fixed.
